AWSTemplateFormatVersion: "2010-09-09"
Description: "Task and service definition with FARGATE"

Parameters:

  ContainerImage:
    Type: String
    Description: "The docker image's cooridinates"
    Default: "128157188766.dkr.ecr.us-east-1.amazonaws.com/presidents"

  ClusterArn:
    Type: String
    Description: "The ECS Cluster ARN"
    Default: "arn:aws:ecs:us-east-1:128157188766:cluster/RothsmithECSCluster"

  ExecutionRoleArn:
    Type: String
    Description: "The ARN of the task execution role"
    Default: "arn:aws:iam::128157188766:role/AWSECSTaskExecutionRole"

  Owner:
    Type: String
    Description: "Owner/Progenitor of the stack"
    Default: "drothauser"  

  SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: "Security Groups for ECS instances"

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: "Subnets from which to launch the ECS instances from"

  TargetGroupArn:
    Type: String
    Description: "The target group ARN of the application load balancer"

Resources:
    CWLoggroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: ecs-presidents

    TaskDefinition:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions: 
              - 
                Essential: true
                Image: !Ref ContainerImage
                LogConfiguration: 
                    LogDriver: "awslogs"
                    Options: 
                        awslogs-group: !Ref CWLoggroup
                        awslogs-region: !Ref AWS::Region
                        awslogs-stream-prefix: "ecs"
                Name: "presidents"
                PortMappings: 
                  - 
                    ContainerPort: 8080
                    HostPort: 8080
                    Protocol: "tcp"
            Family: "presidents"
            TaskRoleArn: "arn:aws:iam::128157188766:role/DevOps"
            ExecutionRoleArn: "arn:aws:iam::128157188766:role/DevOps"
            NetworkMode: "awsvpc"
            RequiresCompatibilities: 
              - "FARGATE"
            Cpu: "256"
            Memory: "512"

    ServiceDefinition:
        Type: "AWS::ECS::Service"
        Properties:
            ServiceName: "presidents"
            Cluster: !Ref ClusterArn
            LoadBalancers: 
              - 
                TargetGroupArn: !Ref TargetGroupArn
                ContainerName: "presidents"
                ContainerPort: 8080
            DesiredCount: 1
            LaunchType: "FARGATE"
            PlatformVersion: "1.4.0"
            TaskDefinition: !Ref TaskDefinition
            DeploymentConfiguration: 
                MaximumPercent: 200
                MinimumHealthyPercent: 100
            NetworkConfiguration: 
              AwsvpcConfiguration: 
                AssignPublicIp: "ENABLED"
                SecurityGroups: !Ref SecurityGroups
                Subnets: !Ref Subnets
            HealthCheckGracePeriodSeconds: 300
            SchedulingStrategy: "REPLICA"

Outputs:
  PresidentsTaskDefinition:
    Description: The created name of the ECS TaskDefinition 
    Value: !Ref TaskDefinition

  PresidentsService:
    Description: "The ECS service"
    Value: !Ref ServiceDefinition