AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create ECS Task Execution Role"

Parameters:

  Owner:
    Type: String
    Description: "Owner/Progenitor of the stack"
    Default: "drothauser" 
    
  Project:
    Type: String
    Description: "Project name"
    Default: "Presidents"  

  RootStack:
    Type: String
    Description: "The parent stack"
    Default: "parent"

Resources:
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: "The ECS task execution Role"
      RoleName: AWSECSTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags: 
        - 
          Key: "Project"
          Value: !Ref Project
        - 
          Key: "Environment"
          Value: "dev"
        - 
          Key: "createdBy"
          Value: !Ref Owner
        - 
          Key: "Name"
          Value: "AWSECSTaskExecutionRole"
          
Outputs:
  ECSTaskExecutionRole:
    Description: "The ECS Task Execution Role"
    Value: !Ref ECSTaskExecutionRole
    Export: 
      Name: !Sub "${RootStack}-ecs-role"