AWSTemplateFormatVersion: "2010-09-09"
Description: NCCT Stack
Parameters:
  ElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  ElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  Ec2KeyPair: 
    Type: String
    Description: Provides the name of the EC2 key pair
  Ec2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  Ec2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  S3Bucket:
    Type: String
    Default: ncct-cloudformation-templates
    Description: The S3 bucket containing CloudFormation templates
  Server:
    Type: String
    Default: BIN
    AllowedValues: 
      - ALL
      - BIN
      - DMS
      - Fusion
      - SMS      
    Description: Server to create
Mappings:
  NcctMap: 
    BIN: 
      ami: "ami-dddfb8bc"
      role: "DevOps"
      scaling: "1,1,1"
      type: "t2.micro"
      name: BIN
      owner: douglas.rothauser@caci.com
      description: Binary Adapter Server
      protocol: TCP
      elbPort: '3389'
      ec2Port: '3389'
      configFile: 'binconfig.xml'
    Fusion: 
      ami: "ami-dddfb8bc"
      role: "DevOps"
      scaling: "1,1,1"
      type: "t2.micro"
      name: Fusion
      owner: douglas.rothauser@caci.com
      description: Fusion Server
      protocol: TCP
      elbPort: '3389'
      ec2Port: '3389'
      configFile: 'fusionconfig.xml'
Conditions: 
  CreateBIN: !Equals [ !Ref Server, BIN ]
Resources:
  BINServer:
    Type: AWS::CloudFormation::Stack
    Condition: CreateBIN
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://s3.us-gov-west-1.amazonaws.com/'
          - !Ref S3Bucket
          - '/ncct-service.yaml'
      Parameters:
        ElbSNs: !Join [ ",", !Ref ElbSNs]
        ElbSGs: !Join [ ",", !Ref ElbSGs]
        Ec2SNs: !Join [ ",", !Ref Ec2SNs]
        Ec2SGs: !Join [ ",", !Ref Ec2SGs]
        Ec2KeyPair: !Ref Ec2KeyPair
        Facing: private
        AmiId: !FindInMap
        - NcctMap
        - BIN
        - ami
        AmiId: !FindInMap
        - NcctMap
        - BIN
        - ami
        Ec2Role: !FindInMap
        - NcctMap
        - BIN
        - role
        Ec2Type: !FindInMap
        - NcctMap
        - BIN
        - type
        Ec2Name: !FindInMap
        - NcctMap
        - BIN
        - name
        Ec2Owner: !FindInMap
        - NcctMap
        - BIN
        - owner
        Ec2Desc: !FindInMap
        - NcctMap
        - BIN
        - description        
        Scaling: !FindInMap
        - NcctMap
        - BIN
        - scaling
        ElbPort: !FindInMap
        - NcctMap
        - BIN
        - elbPort
        Ec2Port: !FindInMap
        - NcctMap
        - BIN
        - ec2Port
        Protocol: !FindInMap
        - NcctMap
        - BIN
        - protocol
        ConfigFile: !FindInMap
        - NcctMap
        - BIN
        - configFile

        