AWSTemplateFormatVersion: "2010-09-09"
Description: NCCT service resource including launch configuration and autoscaling resources
Parameters:
  ConfigFile:
    Type: String
    Description: Configuration XML file used by ncctconfig.ps1
  Ec2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  Ec2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  AmiId:
    Type: String
    Description: Amazon Machine Image ID
  Ec2Role:
    Type: String
    Description: The EC2 Role/Profile name
  Ec2Type:
    Type: String
    Description: The EC2 Instance Type
  ResourcePrefix:
    Type: String
    Default: NCCT
    Description: The prefix for resource names
  SvcAbbr:
    Type: String
    Description: Service abbreviation e.g. SMS, BIN, etc.   
  Ec2Owner:
    Type: String    
    Description: The administrator of this instance's email address
  NightShutdown:
    Type: String
    Default: "false"
    Description: Flag to indicate that the server should be automatically stopped or terminated after business hours
  Ec2Desc:
    Type: String
    Description: EC2 instance's description
  Ec2KeyPair: 
    Type: String
    Description: Provides the name of the Amazon EC2 key pair
  Ec2Port:
    Type: String
    Default: '80'
    Description: TCP port that the application deployed on the EC2 instance listens on
  ElbName:
    Type: String
    Description: Load Balancer name
  ElbDnsKVPs:
    Type: String
    Description: All load balancer DNS names
  Scaling:
    Type: CommaDelimitedList
    Description: Scaling dimensions of the Autoscaling Group - min, max, desired
Conditions: 
  NoLoadBalancer: !Equals [ !Ref ElbName, NA ]
Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !Ref Ec2Role
      InstanceType: !Ref Ec2Type
      ImageId: !Ref AmiId
      KeyName: !Ref Ec2KeyPair
      SecurityGroups: !Ref Ec2SGs      
      UserData:
        "Fn::Base64":
          !Sub |
          <powershell>
            $region = "${AWS::Region}"
            $bucket = "ncct-scripts"
            $scriptsDir = "C:\Scripts\"

            $objects = Get-S3Object -BucketName $bucket -Region $region

            foreach($object in $objects) {
              $localFileName = $object.Key 
              if ($localFileName -ne '') {
                $localFilePath = Join-Path $scriptsDir $localFileName
                Copy-S3Object -BucketName $bucket -Key $object.Key -LocalFile $localFilePath -Region $region
              }
            }

            Set-Location -Path $scriptsDir
            $ncctElbDnsNames = "${ElbDnsKVPs}"
            $elbName = ConvertFrom-StringData -StringData $ncctElbDnsNames

            & .\NcctConfig.ps1 $elbName ${ConfigFile}

            Write-Host "*** NCCT TouchPoint configuration completed ***"  

          </powershell>
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      DesiredCapacity: !Select [ "2", !Ref Scaling ]
      HealthCheckGracePeriod: 300
      LoadBalancerNames: 
      - !If [NoLoadBalancer, !Ref "AWS::NoValue", Ref: ElbName]
      MinSize: !Select [ "0", !Ref Scaling ]
      MaxSize: !Select [ "1", !Ref Scaling ]
      VPCZoneIdentifier: !Ref Ec2SNs
      HealthCheckType: "ELB"
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref ResourcePrefix, !Ref SvcAbbr]]
          PropagateAtLaunch: "true"
        - Key: Owner
          Value: !Ref Ec2Owner
          PropagateAtLaunch: "true"
        - Key: Description
          Value: !Join ["", [!Ref Ec2Desc, "Auto Scaling Group"]]
          PropagateAtLaunch: "true"
        - Key: nightShutdown
          Value: !Ref NightShutdown
          PropagateAtLaunch: "true"
