AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  ElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  ElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  Ec2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  Ec2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  AmiId:
    Type: String
    Description: Amazon Machine Image ID
  Ec2Role:
    Type: String
    Description: The EC2 Role/Profile name
  Ec2Type:
    Type: String
    Description: The EC2 Instance Type
  Ec2Name:
    Type: String
    Description: Tag name for the EC2 instance    
  Ec2Owner:
    Type: String    
    Description: The administrator of this instance's email address
  Ec2Desc:
    Type: String
    Description: EC2 instance's description
  Ec2Port:
    Type: String
    Description: The port the EC2 instance's application listens on
  Scaling:
    Type: CommaDelimitedList
    Description: Scaling dimensions of the Autoscaling Group - min, max, desired
  Facing:
    Type: String
    Default: public
    AllowedValues:
      - public
      - private
    Description: Will this service be public facing or in a private network layer
  ServiceCode:
    Type: String
    Description: The service code to identify what initialization script to run in userdata
  DNSKeyPairs:
    Type: String
    Description: List of service key pairs to append to the /etc/sysconfig/httd httpd file
Mappings:
  LayerMap:
    public:
      scheme: internet-facing
    private:
      scheme: internal
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:      
      HealthCheck:
        HealthyThreshold: '3'
        Interval: '10'
        Target: !Join ["", ["HTTP:", !Ref Ec2Port, "/"]]
        Timeout: '5'
        UnhealthyThreshold: '5'
      Listeners:
      - LoadBalancerPort: !Ref Ec2Port
        InstancePort: !Ref Ec2Port
        Protocol: HTTP
      Scheme: !FindInMap
        - LayerMap
        - !Ref Facing
        - scheme
      SecurityGroups: !Ref ElbSGs
      Subnets: !Ref ElbSNs
      Tags:
      - Key: Name
        Value: !Ref Ec2Name
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !Ref Ec2Role
      InstanceType: !Ref Ec2Type
      ImageId: !Ref AmiId
      KeyName: RothsmithKeyPair
      SecurityGroups: !Ref Ec2SGs
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            
            script="rothsmith-$serviceCode.sh"
            cd /tmp
            aws s3 cp s3://rothsmith-scripts/$script . --region ${AWS::Region}               
 
            source ./$script ${DNSKeyPairs}  &> $script.log

            # yum update -y httpd            
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      DesiredCapacity: !Select [ "2", !Ref Scaling ]
      HealthCheckGracePeriod: 300
      LoadBalancerNames:
      - Ref: LoadBalancer
      MinSize: !Select [ "0", !Ref Scaling ]
      MaxSize: !Select [ "1", !Ref Scaling ]
      VPCZoneIdentifier: !Ref Ec2SNs
      HealthCheckType: "ELB"
      Tags:
        - Key: Name
          Value: !Ref Ec2Name
          PropagateAtLaunch: "true"
        - Key: Owner
          Value: !Ref Ec2Owner
          PropagateAtLaunch: "true"
        - Key: Description
          Value: !Ref Ec2Desc
          PropagateAtLaunch: "true"
Outputs:
  URL:
    Description: URL of the sample website
    Value: !Join ['', ['http://', !GetAtt [LoadBalancer, DNSName]]]
