AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  PubElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  PubElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  PubEc2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  PubEc2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  S3Bucket:
    Type: String
    Default: rothsmith-cloudformation
    Description: The S3 bucket containing CloudFormation templates
Mappings:
  TierMap: 
    public: 
      ami: "ami-0151f162d1ff20101"
      role: "CloudWatch"
      scaling: "1,1,1"
      type: "t2.micro"
      name: DMZ server
      owner: drothauser@yahoo.com
      description: DMZ Apache Web Server
    private: 
      ami: "ami-07c8b576e965e389e"
      role: "CloudWatch"
      scaling: "1,1,1"
      type: "t2.micro"
      name: Application server
      owner: drothauser@yahoo.com
      description: Tomcat Server
Resources:
  PublicTier:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref S3Bucket
          - '/rothsmith-service.yaml'
      Parameters:
        ElbSNs: !Join [ ",", !Ref PubElbSNs]
        ElbSGs: !Join [ ",", !Ref PubElbSGs]
        Ec2SNs: !Join [ ",", !Ref PubEc2SNs]
        Ec2SGs: !Join [ ",", !Ref PubEc2SGs]
        AmiId: !FindInMap
        - TierMap
        - public
        - ami
        AmiId: !FindInMap
        - TierMap
        - public
        - ami
        Ec2Role: !FindInMap
        - TierMap
        - public
        - role
        Ec2Type: !FindInMap
        - TierMap
        - public
        - type
        Ec2Name: !FindInMap
        - TierMap
        - public
        - name
        Ec2Owner: !FindInMap
        - TierMap
        - public
        - owner
        Ec2Desc: !FindInMap
        - TierMap
        - public
        - description
        Facing: public
        Scaling: !FindInMap
        - TierMap
        - public
        - scaling

        