AWSTemplateFormatVersion: "2010-09-09"
Description: Windows Server Template
Parameters:
  AmiId:
    Type: String
    Default: ami-04bfee437f38a691e
    Description: Amazon Machine Image ID
  Ec2Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-5d163f70
    Description: EC2 Instance Subnet
  Ec2SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: linux-sg
    Description: Security Groups for EC2 instance 
  EC2KeyPair: 
    Type: String
    Default: RothsmithKeyPair
    Description: Provides the name of the Amazon EC2 key pair
  EC2Profile: 
    Type: String
    Default: DevOps
    Description: The profile/role for this EC2 instance
  AdsStack:
    Type: String
    Default: 'ROTHSMITH-ADS'
    Description: The Amazon Directory Service stack to obtain exported values from
  AdsUser:
    Type: String
    Default: 'Administrator'
    Description: The Amazon Directory Service administrator user id
  AdsPassword:
    Type: String
    Default: 'Password12345!'
    Description: The Amazon Directory Service administrator user id
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Authentication:  
        S3AccessCreds:  
            type: "S3"  
            roleName: !Ref EC2Profile  
            buckets:  
                - "rothsmith-scripts"
      AWS::CloudFormation::Init: 
        configSets:
          ascending: 
            - "config1"
            - "config2"
        config1: 
          packages:
            yum: 
              realmd: []
              krb5-workstation: []
              sssd: []
              oddjob: []
              oddjob-mkhomedir: []
              samba-common-tools: []              
          services: 
            sysvinit: 
              sssd: 
                enabled: "true"
                ensureRunning: "true"
              realmd: 
                enabled: "true"
                ensureRunning: "true"
        config2:
          files:
            /tmp/domjoin.sh: 
              source: "https://s3.amazonaws.com/rothsmith-scripts/domjoin.sh"                         
              mode: "000744"
              owner: "root"
              group: "root"
              authentication: "S3AccessCreds"        
          commands:               
            1-join-domain: 
              command: './domjoin.sh $DomainName $DnsPrimaryIP $DnsSecondaryIP $AdsUserName $AdsPasswd'
              env: 
                AdsUserName: 
                  !Ref AdsUser
                AdsPasswd: 
                  !Ref AdsPassword
                DomainName: 
                  "Fn::ImportValue": !Sub "${AdsStack}-Name"
                DnsPrimaryIP: 
                  "Fn::ImportValue": !Sub "${AdsStack}-DnsPrimaryIP"
                DnsSecondaryIP: 
                  "Fn::ImportValue": !Sub "${AdsStack}-DnsSecondaryIP"
              cwd: "/tmp"
    Properties:
      IamInstanceProfile: !Ref EC2Profile
      InstanceType: t2.micro
      ImageId: !Ref AmiId
      KeyName: !Ref EC2KeyPair
      #NetworkInterfaces: 
      #  - AssociatePublicIpAddress: "true"
      #    DeviceIndex: "0"
      #    GroupSet: !Ref Ec2SecurityGroups
      #    SubnetId: !Ref Ec2Subnet
      SecurityGroupIds: !Ref Ec2SecurityGroups
      SubnetId: !Ref Ec2Subnet
      Tags:
        - Key: Name
          Value: Linux Server
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          /opt/aws/bin/cfn-init -v -c ascending -s ${AWS::StackName} -r Ec2Instance --region=${AWS::Region}
          dirName=${AdsStack}-Name
          dirId=${AdsStack}-Id
          primaryIP=${AdsStack}-DnsPrimaryIP
          secondaryIP=${AdsStack}-DnsSecondaryIP
          echo "NAME *** $dirName" > /tmp/userdata.log
          echo "ID *** $dirId" >> /tmp/userdata.log
          echo "1st *** $primaryIP" >> /tmp/userdata.log 
          echo "2nd *** $secondaryIP" >> /tmp/userdata.log
          
