AWSTemplateFormatVersion: "2010-09-09"
Description: Windows Server Template
Parameters:
  AmiId:
    Type: String
    Default: ami-0cd958afb1ce79731
    Description: Amazon Machine Image ID
  Ec2Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-1626bf2a
    Description: EC2 Instance Subnet
  Ec2SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-c6f9e6ba
    Description: Security Groups for EC2 instance 
  Ec2KeyPair: 
    Type: String
    Default: RothsmithKeyPair
    Description: Provides the name of the Amazon EC2 key pair
  Ec2Profile: 
    Type: String
    Default: DevOps
    Description: The profile/role for this EC2 instance
  Ec2Name:
    Type: String
    Default: WIN-QUICKEN
    Description: Name of the EC2 instance
  Ec2Owner:
    Type: String
    Default: drothauser
    Description: Email address of the person owning this EC2 instance
  Ec2Desc:
    Type: String
    Default: Work Windows Machine
    Description: Description of this EC2 instance
Resources:  
  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Authentication:  
        S3AccessCreds:  
            type: "S3"  
            roleName: !Ref Ec2Profile  
            buckets:  
                - "rothsmith-software"
      AWS::CloudFormation::Init:     
        config: 
          packages:
            msi: 
              "urlrewrite" : "https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi"
          files:
            C:\DropboxInstaller.exe: 
              source: "https://s3.amazonaws.com/rothsmith-software/DropboxInstaller.exe"                         
              authentication: "S3AccessCreds"  
          commands:
            0-install-dropbox: 
              command: 'C:\DropboxInstaller.exe'  
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 40
            VolumeType: gp2
      IamInstanceProfile: !Ref Ec2Profile
      InstanceType: t2.small
      ImageId: !Ref AmiId
      KeyName: !Ref Ec2KeyPair
      SecurityGroupIds: !Ref Ec2SecurityGroups
      SubnetId: !Ref Ec2Subnet
      Tags:
        - Key: Name
          Value: !Ref Ec2Name
        - Key: Owner
          Value: !Ref Ec2Owner
        - Key: Description
          Value: !Ref Ec2Desc
      UserData:
        "Fn::Base64":
          !Sub |
            <script>             
              C:\PROGRA~1\Amazon\cfn-bootstrap\cfn-init.exe -v -s ${AWS::StackName} -r Ec2Instance --region=${AWS::Region}
            </script>
