AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  PubElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  PubElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  PubEc2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  PubEc2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  AmiId:
    Type: String
    Description: Amazon Machine Image ID
  Ec2Role:
    Type: String
    Default: CloudWatch
    Description: The EC2 Role/Profile name
  Ec2Type:
    Type: String
    Default: t2.micro
    Description: The EC2 Instance Type
  S3Bucket:
    Type: String
    Default: rothsmith-cloudformation
    Description: The S3 bucket containing CloudFormation templates
Mappings:
  TierMap: 
    public: 
      ami: "ami-0151f162d1ff20101"
      role: "CloudWatch"
      type: "t2.micro"
    private: 
      ami: "ami-07c8b576e965e389e"
      role: "CloudWatch"
      type: "t2.micro"
Resources:
  PublicTier:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref S3Bucket
          - '/rothsmith-service.yaml'
      Parameters:
        ElbSNs: !Join [ ",", !Ref PubElbSNs]
        ElbSGs: !Join [ ",", !Ref PubElbSGs]
        Ec2SNs: !Join [ ",", !Ref PubEc2SNs]
        Ec2SGs: !Join [ ",", !Ref PubEc2SGs]
        AmiId: !Ref AmiId
        Ec2Role: !Ref Ec2Role
        Ec2Type: !Ref Ec2Type
        