AWSTemplateFormatVersion: "2010-09-09"
Description: NCCT Directory Service
Parameters:
  SubnetsManagement:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Default: "subnet-3bac0a4d,subnet-bca20dd8"
    Description: Subnet IDs for management instances
  ADPassword:
    Type: String
    #AllowedPattern: (?=^.{8,64}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9\s])(?=.*[a-z])|(?=.*[^A-Za-z0-9\s])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9\s]))^.*
    #ConstraintDescription: Password must be complex. To generate: https://onlinestringtools.com/generate-string-from-regex
    #Default: h|.%372K1&GC,)dyGTg
    Description: Active Directory administration password
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID for the directory server
Resources:
  RothsmithDirectory: 
    Type: AWS::DirectoryService::SimpleAD
    Properties: 
      CreateAlias: true
      Name: "rothsmith.net"
      Password: 
        Ref: ADPassword
      Size: "Small"
      VpcSettings: 
        SubnetIds: !Ref SubnetsManagement
        VpcId: 
          Ref: VpcId
Outputs:
  Alias:
    Description: Directory Alias
    Value: !GetAtt RothsmithDirectory.Alias
    Export:
      Name: !Sub ${AWS::StackName}-Alias
  DnsIpAddresses:
    Description: The IP addresses of the DNS servers for the directory
    Value: !Join [",", !GetAtt RothsmithDirectory.DnsIpAddresses]
    Export:
      Name: !Sub ${AWS::StackName}-DnsIpAddresses