AWSTemplateFormatVersion: "2010-09-09"
Description: NCCT Directory Service
Parameters:
  SubnetsManagement:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Default: "subnet-3bac0a4d,subnet-bca20dd8"
    Description: Management SubnetIds for SMC (Help Desk Management)
  SecurityGroupsManagement:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-7da2f819
    Description: Management Security Groups for SMC (Help Desk Management)
  ADPassword:
    Type: String
    AllowedPattern: (?=^.{8,64}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9\s])(?=.*[a-z])|(?=.*[^A-Za-z0-9\s])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9\s]))^.*
    ConstraintDescription: Password must be complex
    Default: Tb+KYq\TEZ )~nC~3R2M
    Description: Active Directory administration password
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID for the directory server
Resources:
  NcctDirectory: 
    Type: AWS::DirectoryService::SimpleAD
    Properties: 
      Name: "ncct.caci.com"
      Password: 
        Ref: ADPassword
      Size: "Small"
      VpcSettings: 
        SubnetIds: !Ref SubnetsManagement
        VpcId: 
          Ref: VpcId