AWSTemplateFormatVersion: 2010-09-09
Description: RDS Stack for Rothsmith Applications
Parameters:
  VPCStack:
    Type: String
    Default: 'ROTHSMITH-VPC'
    Description: The VPC stack to obtain exported values from
  ResourcePrefix:
    Type: String
    Default: ROTHSMITH
    Description: The prefix for resource names
  DbAbbr:
    Type: String
    Description: Database abbreviation
    Default: PREZ 
  RdsOwner:
    Type: String
    Default: drothauser@yahoo.com
    Description: Email address for the administrator of this RDS instance
  RdsDesc:
    Type: String
    Description: RDS database instance description
  #RdsSNs:
  #  Description: Subnets to be included in RDS DB Subnet Group
  #  Type: List<AWS::EC2::Subnet::Id>
  #RdsSGs:
  #  Description: Security groups for RDS DB instance
  #  Type: List<AWS::EC2::SecurityGroup::Id>
  RdsSnapshotId:
    Description: RDS Snapshot to build DB instance from. An empty string indicates build new db.
    Type: String
    #Default: arn:aws-us-gov:rds:us-gov-west-1:720711321849:snapshot:hobbsrds-final-snapshot
  DbName:
    Description: Name for new RDS database
    Type: String
    Default: PRESIDENTS
  DbInstanceClass:
    Description: The database instance class
    Type: String
    #Default: db.m4.large 
    Default: db.t2.micro 
  DbInstancePort:
    Type: String
    Default: '5432'
    Description: Port for the DB instance
  DbUsername:
    Description: RDS Database username
    Type: String    
    AllowedPattern: ^[a-zA-Z0-9_\\-]{8,}$
    ConstraintDescription: Password must be at least 8 alphanumeric characters long (_ and - characters allowed)
    Default: drothauser
  DbPassword:
    Description: RDS Database password
    Type: String
    NoEcho: true
Conditions:
  HasDbSnapshotId: !Not [!Equals [!Ref RdsSnapshotId, '']]
Resources:
  RdsDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Database subnet group
      DBSubnetGroupName: !Join ["-", [!Ref ResourcePrefix, !Ref DbAbbr, "SubnetGroup"]]      
      #SubnetIds: !Ref RdsSNs
      SubnetIds: 
      - 'Fn::ImportValue': 
          !Sub '${VPCStack}-PrivateSubnet1'
      - 'Fn::ImportValue': 
          !Sub '${VPCStack}-PrivateSubnet2'
      Tags:
      - Key: Name
        Value: !Join ["-",[!Ref ResourcePrefix, !Ref DbAbbr, "SubnetGroup"]] 
      - Key: Description
        Value: !Join ["", [!Ref RdsDesc, "Subnet group"]]
      - Key: Owner
        Value: RdsOwner
  RdsDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DbInstanceClass
      DBInstanceIdentifier: !Join ["-",[!Ref ResourcePrefix, !Ref DbAbbr]]
      DBName: !If [HasDbSnapshotId, !Ref "AWS::NoValue", !Ref DbName]
      DBSnapshotIdentifier: !If [HasDbSnapshotId, !Ref RdsSnapshotId, !Ref "AWS::NoValue"]
      DBSubnetGroupName: !Ref RdsDbSubnetGroup
      Engine: postgres
      Iops: 1000
      LicenseModel: postgresql-license
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      Port: !Ref DbInstancePort
      PubliclyAccessible: false
      StorageEncrypted: false
      StorageType: io1
      #VPCSecurityGroups: !Ref RdsSGs
      VPCSecurityGroups: 
      - 'Fn::ImportValue': 
          !Sub '${VPCStack}-PrivateSubnetInstanceSG'
      Tags:
      - Key: Name
        Value: !Join ["-",[!Ref ResourcePrefix, !Ref DbAbbr]]
      - Key: Description
        Value: !Join ["", [!Ref RdsDesc, "DB Instance"]]
      - Key: Owner
        Value: !Ref RdsOwner
Outputs:
  DbInstanceName:
    Description: RDS Database Instance Resource
    Value: !Ref RdsDbInstance
  DbInstanceDnsName:
    Description: DNS Name for RDS Database Instance
    Value: !GetAtt RdsDbInstance.Endpoint.Address
  DbInstancePort:
    Description: Port number on which RDS database accepts connections
    Value: !GetAtt RdsDbInstance.Endpoint.Port
  DbInstanceDnsKVP:
    Description: Key-value pair for a DNS entry in a hashtable.
    Value: !Join ["=", [!Join ["-", [!Ref ResourcePrefix, !Ref DbAbbr, "DB"]],  !GetAtt RdsDbInstance.Endpoint.Address]]
    Export:
      Name: !Sub "${AWS::StackName}-DbInstanceDnsKVP"
