AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  PubElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  PubElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  PubEc2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  PubEc2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  AmiId:
    Type: String
    Description: Amazon Machine Image ID
Mappings:
  TierMap: 
    public: 
      ami: "ami-0151f162d1ff20101"
      role: "CloudWatch"
      type: "t2.micro"
    private: 
      ami: "ami-07c8b576e965e389e"
      role: "CloudWatch"
      type: "t2.micro"
Resources:
  PublicTier:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: