AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  ELBSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  ELBSecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  Ec2Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  Ec2SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
Resources:
  DmzELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:      
      #AvailabilityZones: ["us-east-1a"]
      HealthCheck:
        HealthyThreshold: '3'
        Interval: '10'
        Target: HTTP:80/
        Timeout: '5'
        UnhealthyThreshold: '5'
      Instances: 
      #- Ref: Instances
      - Ref: Ec2Instance
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      Scheme: internet-facing
      SecurityGroups: !Ref ELBSecurityGroups
      Subnets: !Ref ELBSubnets
      Tags:
      - Key: Name
        Value: DMZ ELB
  DmzLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: CloudWatch
      InstanceType: t2.micro
      ImageId: ami-0151f162d1ff20101
      KeyName: RothsmithKeyPair
      SecurityGroupIds: !Ref Ec2SecurityGroups      
      Tags:
        - Key: Name
          Value: DMZ Web Server
  DmzASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref DmzLaunchConfiguration
      DesiredCapacity: '1'
      LoadBalancerNames:
      - Ref: DmzELB
      MinSize: '1'
      MaxSize: '1'
      VPCZoneIdentifier: !Ref Ec2Subnets
      HealthCheckType: "EC2"

Outputs:
  URL:
    Description: URL of the sample website
    Value: !Join ['', ['http://', !GetAtt [DmzELB, DNSName]]]