AWSTemplateFormatVersion: 2010-09-09
Description: DNS for rothsmith.net
Parameters:
  AppsStack:
    Type: String
    Default: 'ROTHSMITH-APPS'
    Description: The application stack to obtain exported values from
  WebProxyDNS:
    Type: String
    Description: Web Proxy URL
  NexusDNS:
    Type: String
    Description: Nexus URL
Resources:
  # = = = = = = = = = = = = = = = = = #
  # Root Website
  # = = = = = = = = = = = = = = = = = #
  RootHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: rothsmith.net
      HostedZoneConfig:
        Comment: rothsmith.net
  RothsmithNetA:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: rothsmith.net
      Type: A
      AliasTarget:        
        DNSName: !Join
          - '.'
          - - 'dualstack'
            - !Ref WebProxyDNS
            #- 'Fn::ImportValue': 
            #    !Sub '${AppsStack}-WebProxyDNS'
        EvaluateTargetHealth: false
        HostedZoneId: Z35SXDOTRQ7X7K
      HostedZoneId:
        Ref: RootHostedZone
  NexusRothsmithNetNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: nexus.rothsmith.net
      Type: NS
      HostedZoneId:
        Ref: RootHostedZone
      ResourceRecords: !GetAtt NexusHostedZone.NameServers
      #- ns-441.awsdns-55.com.
      #- ns-1157.awsdns-16.org.
      #- ns-1646.awsdns-13.co.uk.
      #- ns-635.awsdns-15.net.
      TTL: 300
#  JenkinsRothsmithNetNS:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      Name: jenkins.rothsmith.net
#      Type: NS
#      HostedZoneId:
#        Ref: RootHostedZone
#      ResourceRecords:
#      - ns-162.awsdns-20.com.
#      - ns-1760.awsdns-28.co.uk.
#      - ns-1257.awsdns-29.org.
#      - ns-928.awsdns-52.net.
#      TTL: 300
  # = = = = = = = = = = = = = = = = = #
  # Nexus Repository Manager
  # = = = = = = = = = = = = = = = = = #
  NexusHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: nexus.rothsmith.net
      HostedZoneConfig:
        Comment: nexus.rothsmith.net
  NexusRothsmithNetA:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: nexus.rothsmith.net
      Type: A
      AliasTarget:
        DNSName: !Join
          - '.'
          - - 'dualstack'
            - !Ref NexusDNS
            #- 'Fn::ImportValue': 
            #    !Sub '${AppsStack}-NexusDNS'
        EvaluateTargetHealth: false
        HostedZoneId: Z35SXDOTRQ7X7K
      HostedZoneId:
        Ref: NexusHostedZone
  #NexusRothsmithNetSubdomainNS:
  #  Type: AWS::Route53::RecordSet
  #  Properties:
  #    Name: nexus.rothsmith.net
  #    Type: NS
  #    HostedZoneId:
  #      Ref: RootHostedZone
  #    ResourceRecords: !GetAtt NexusRothsmithNetNS.NameServers
  #    TTL: 300
  # = = = = = = = = = = = = = = = = = #
  # Jenkins Continuous Integration
  # = = = = = = = = = = = = = = = = = #
  #JenkinsHostedZone:
  #  Type: AWS::Route53::HostedZone
  #  Properties:
  #    Name: jenkins.rothsmith.net
  #    HostedZoneConfig:
  #      Comment: jenkins.rothsmith.net
  #JenkinsRothsmithNetA:
  #  Type: AWS::Route53::RecordSet
  #  Properties:
  #    Name: jenkins.rothsmith.net
  #    Type: A
  #    AliasTarget:        
  #      DNSName: !Join
  #        - '.'
  #        - - 'dualstack'
  #          - 'Fn::ImportValue': 
  #              !Sub '${AppsStack}-JenkinsDNS'
  #      EvaluateTargetHealth: false
  #      HostedZoneId: Z2DM6YURBQQUN0
  #    HostedZoneId:
  #      Ref: JenkinsHostedZone