AWSTemplateFormatVersion: "2010-09-09"
Description: Windows Server Template
Parameters:
  AmiId:
    Type: String
    Default: ami-69099208
    Description: Amazon Machine Image ID
  Ec2Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-9c37edf8
    Description: EC2 Instance Subnet
  Ec2SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-b5dc32d1
    Description: Security Groups for EC2 instance 
  Ec2KeyPair: 
    Type: String
    Description: Provides the name of the Amazon EC2 key pair
  Ec2Profile: 
    Type: String
    Default: DevOps
    Description: The profile/role for this EC2 instance
  Ec2Name:
    Type: String
    Description: Name of the EC2 instance
  Ec2Owner:
    Type: String
    Description: Email address of the person owning this EC2 instance
  Ec2Desc:
    Type: String
    Description: Description of this EC2 instance
  AdsStackName:
    Type: String
    Default: "NCCT-ADS"
    Description: AWS Directory Service (Active Directory) stack name for importing DNS properties
  # AdsId:
  #   Type: String
  #   Description: AWS Directory Service (Active Directory) Id  
  # AdsName:
  #   Type: String
  #   Description: AWS Directory Service (Active Directory) Name
  # AdsDnsPrimaryIP:
  #   Type: String
  #   Description: AWS Directory Service (Active Directory) primary DNS IP
  # AdsDnsSecondaryIP:
  #   Type: String
  #   Description: AWS Directory Service (Active Directory) secondary DNS IP
Resources:
  SsmDomainDocument:   
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: (Required) The ID of the AWS Directory Service directory.
          directoryName:
            type: String
            description: >-
              (Required) The name of the directory; for example,
              test.example.com
          dnsIpAddresses:
            type: StringList
            default: []
            description: >-
              (Optional) The IP addresses of the DNS servers in the directory.
              Required when DHCP is not configured. Learn more at
              http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_get_dns_addresses.html
            allowedPattern: >-
              ((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
        runtimeConfig:
          'aws:domainJoin':
            properties:
              directoryId: '{{ directoryId }}'
              directoryName: '{{ directoryName }}'
              dnsIpAddresses: '{{ dnsIpAddresses }}'
  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Authentication:  
        S3AccessCreds:  
            type: "S3"  
            roleName: !Ref Ec2Profile  
            buckets:  
                - "rothsmith-scripts"
      AWS::CloudFormation::Init:     
        config: 
          packages:
            msi: 
              "urlrewrite" : "https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi"
          files:
            C:\ADExplorer.exe: 
              source: "https://s3.amazonaws.com/rothsmith-software/ADExplorer.exe"                         
              authentication: "S3AccessCreds"    
    Properties:
      SsmAssociations:
        - DocumentName: !Ref SsmDomainDocument
          AssociationParameters:
            - Key: directoryId
              Value:
                - "Fn::ImportValue": !Sub "${AdsStackName}-Id"
            - Key: directoryName
              Value:
                - "Fn::ImportValue": !Sub "${AdsStackName}-Name"
            - Key: dnsIpAddresses
              Value:
                - "Fn::ImportValue": !Sub "${AdsStackName}-DnsPrimaryIP"
                - "Fn::ImportValue": !Sub "${AdsStackName}-DnsSecondaryIP"
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 40
            VolumeType: gp2
      IamInstanceProfile: !Ref Ec2Profile
      InstanceType: t2.micro
      ImageId: !Ref AmiId
      KeyName: !Ref Ec2KeyPair
      SecurityGroupIds: !Ref Ec2SecurityGroups
      SubnetId: !Ref Ec2Subnet
      Tags:
        - Key: Name
          Value: !Ref Ec2Name
        - Key: Owner
          Value: !Ref Ec2Owner
        - Key: Description
          Value: !Ref Ec2Desc
      UserData:
        "Fn::Base64":
          !Sub |
            <script>             
              C:\PROGRA~1\Amazon\cfn-bootstrap\cfn-init.exe -v -s ${AWS::StackName} -r Ec2Instance --region=${AWS::Region}
            </script>
