AWSTemplateFormatVersion: "2010-09-09"
Description: DMZ ELB
Parameters:
  PubElbSNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC) for your ELB
  PubElbSGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: The list of Security Groups used by your ELB
  PubEc2SNs:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: EC2 Instance Subnets
  PubEc2SGs:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Security Groups for EC2 instance 
  AmiId:
    Type: String
    Description: Amazon Machine Image ID
Mappings:
  TierMap: 
    public: 
      ami: "ami-0151f162d1ff20101"
      role: "CloudWatch"
      type: "t2.micro"
    private: 
      ami: "ami-07c8b576e965e389e"
      role: "CloudWatch"
      type: "t2.micro"
Resources:
  DmzELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:      
      HealthCheck:
        HealthyThreshold: '3'
        Interval: '10'
        Target: HTTP:80/
        Timeout: '5'
        UnhealthyThreshold: '5'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      Scheme: internet-facing
      SecurityGroups: !Ref PubElbSGs
      Subnets: !Ref PubElbSNs
      Tags:
      - Key: Name
        Value: DMZ ELB
  DmzLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !FindInMap
        - TierMap
        - public
        - role 
      InstanceType: !FindInMap
        - TierMap
        - public
        - type 
      ImageId: !FindInMap
        - TierMap
        - public
        - ami 
      KeyName: RothsmithKeyPair
      SecurityGroups: !Ref PubEc2SGs
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            yum update -y httpd
  DmzASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref DmzLaunchConfiguration
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 300
      LoadBalancerNames:
      - Ref: DmzELB
      MinSize: '1'
      MaxSize: '1'
      VPCZoneIdentifier: !Ref PubEc2SNs
      HealthCheckType: "ELB"
      Tags:
        - Key: Name
          Value: DMZ AutoScaling Group
          PropagateAtLaunch: "true"

Outputs:
  URL:
    Description: URL of the sample website
    Value: !Join ['', ['http://', !GetAtt [DmzELB, DNSName]]]