AWSTemplateFormatVersion: "2010-09-09"
Description: Standup a Windows instance stack for the purpose of generating a NCCT AMI using AWS VM Import Export
Parameters:
  AmiId:
    Type: String
    Default: ami-69099208
    Description: Amazon Machine Image ID
  Ec2Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-9c37edf8
    Description: EC2 Instance Subnet
  Ec2SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-b5dc32d1
    Description: Security Groups for EC2 instance 
  Ec2KeyPair: 
    Type: String
    Description: Provides the name of the Amazon EC2 key pair
  Ec2Profile: 
    Type: String
    Default: DevOps
    Description: The profile/role for this EC2 instance
  Ec2Name:
    Type: String
    Description: Name of the EC2 instance
  Ec2Owner:
    Type: String
    Description: Email address of the person owning this EC2 instance
  Ec2Desc:
    Type: String
    Description: Description of this EC2 instance  
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 80
            VolumeType: gp2
      IamInstanceProfile: !Ref Ec2Profile
      InstanceType: m4.xlarge
      ImageId: !Ref AmiId
      KeyName: !Ref Ec2KeyPair
      SecurityGroupIds: !Ref Ec2SecurityGroups
      SubnetId: !Ref Ec2Subnet
      Tags:
        - Key: Name
          Value: !Ref Ec2Name
        - Key: Owner
          Value: !Ref Ec2Owner
        - Key: Description
          Value: !Ref Ec2Desc
      UserData:
        "Fn::Base64":
          !Sub |
          <powershell>

            $NCCT_Template_Bucket = "ncct-cloudformation-templates";
            $NCCT_Scripts_Dir = "UserdataScripts";
            $Region = "us-gov-west-1";

            Function LaunchScript ([string]$Script)
            {
              Read-S3Object `
                -BucketName $NCCT_Template_Bucket `
                -Key $NCCT_Scripts_Dir/$Script `
                -File $env:Temp\$Script `
                -Region $Region
              & $env:Temp\$Script
            }

            LaunchScript "cli-install.ps1"
            LaunchScript "caciuserdata.ps1"

          </powershell>